version: "3.8"
name: monitorss-prod
services:
  bot-presence-service:
    extends:
      file: ./docker-compose.yml
      service: bot-presence-service
    build:
      context: services/bot-presence
      dockerfile: Dockerfile
      target: prod
    command: ["node", "dist/main.js"]
    env_file:
      - ./.env.prod

  feed-requests-redis-cache:
    extends:
      file: ./docker-compose.yml
      service: feed-requests-redis-cache
  
  rabbitmq-broker:
    extends:
      file: ./docker-compose.yml
      service: rabbitmq-broker

  mongo:
    extends:
      file: ./docker-compose.yml
      service: mongo
  
  feed-requests-postgres-db:
    extends:
      file: ./docker-compose.yml
      service: feed-requests-postgres-db
      
  user-feeds-postgres-db:
    extends:
      file: ./docker-compose.yml
      service: user-feeds-postgres-db

  discord-rest-listener-service:
    extends:
      file: ./docker-compose.yml
      service: discord-rest-listener-service
    build:
      context: services/discord-rest-listener
      dockerfile: Dockerfile
      target: prod
    command: ["node", "build/app.js"]
    env_file:
      - ./.env.prod

  feed-requests-service:
    extends:
      file: ./docker-compose.yml
      service: feed-requests-service
    build:
      context: services/feed-requests
      dockerfile: Dockerfile
      target: prod
    command: ["node", "dist/main.js"]
    env_file:
      - ./.env.prod
    environment:
      - NODE_ENV=production

  feed-requests-api:
    extends:
      file: ./docker-compose.yml
      service: feed-requests-api
    build:
      context: services/feed-requests
      dockerfile: Dockerfile
      target: prod
    command: ["node", "dist/main.js"]
    env_file:
      - ./.env.prod
    environment:
      - NODE_ENV=production

  feed-requests-postgres-migration:
    extends:
      file: ./docker-compose.yml
      service: feed-requests-postgres-migration
    build:
      context: services/feed-requests
      dockerfile: Dockerfile
      target: build
    command: "npm run migration:local:up"
    env_file:
      - ./.env.prod

  user-feeds-service:
    extends:
      file: ./docker-compose.yml
      service: user-feeds-service
    build:
      context: services/user-feeds
      dockerfile: Dockerfile
      target: prod
    command: ["node", "dist/main.js"]
    env_file:
      - ./.env.prod

  user-feeds-postgres-migration:
    extends:
      file: ./docker-compose.yml
      service: user-feeds-postgres-migration
    env_file:
      - ./.env.prod

  legacy-feed-bulk-converter-service:
    extends:
      file: ./docker-compose.yml
      service: legacy-feed-bulk-converter-service
    build:
      context: services/backend-api
      dockerfile: dockerfiles/legacy-feed-bulk-converter/Dockerfile
      target: prod
    command: ["node", "dist/scripts/legacy-feed-bulk-converter.js"]
    env_file:
      - ./.env.prod

  schedule-emitter-service:
    extends:
      file: ./docker-compose.yml
      service: schedule-emitter-service
    build:
      context: services/backend-api
      dockerfile: dockerfiles/schedule-emitter/Dockerfile
      target: prod
    command: ["node", "dist/scripts/schedule-emitter.js"]
    env_file:
      - ./.env.prod

  monolith:
    build:
      context: services/backend-api
      dockerfile: dockerfiles/web/mixed.Dockerfile
      target: prod
    restart: on-failure:3
    depends_on:
      - mongo
      - user-feeds-service
      - feed-requests-service
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod
    environment:
      - BACKEND_API_NODE_ENV=local
      - BACKEND_API_PORT=8000
      - BACKEND_API_DEFAULT_MAX_FEEDS=999999
      - BACKEND_API_MONGODB_URI=mongodb://mongo:27017/rss
      - BACKEND_API_USER_FEEDS_API_HOST=http://user-feeds-service:5000
      - BACKEND_API_FEED_REQUESTS_API_HOST=http://feed-requests-api:5000
      - BACKEND_API_LOGIN_REDIRECT_URI=http://localhost:8000
      - BACKEND_API_DISCORD_REDIRECT_URI=http://localhost:8000/api/v1/discord/callback-v2
      - BACKEND_API_DEFAULT_REFRESH_RATE_MINUTES=0.1
      - BACKEND_API_FEED_USER_AGENT=MonitoRSS
      - BACKEND_API_RABBITMQ_BROKER_URL=amqp://guest:guest@rabbitmq-broker:5672/
      - BACKEND_API_USER_FEEDS_API_KEY=user-feeds-api-key
      - BACKEND_API_FEED_REQUESTS_API_KEY=feed-requests-api-key
      - LOG_LEVEL=info
    command: ["node", "dist/main.js"]
    networks:
      - monitorss-default


volumes:
  mongodb-data:
  feed-requests-postgres-data:
  user-feeds-postgres-data:
  feed-requests-redis-data:
    driver: local

networks:
  monitorss-default:
    driver: bridge